services:
  - type: web
    name: financial-doc-ai
    env: python
    plan: free

    buildCommand: |
      apt-get update
      
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm

    startCommand: |
      gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10